all:
	./src/main/protoc -I=./src/main --java_out=./src/main/java ./src/main/resources/amazon_ups.proto
	./src/main/protoc -I=./src/main --java_out=./src/main/java ./src/main/resources/world_amazon.proto
	./src/main/protoc -I=./src/main --java_out=./src/main/java ./src/main/resources/world_ups.proto
i:
	./src/main/protoc -I=./src/main --java_out=./src/main/java ./src/main/resources/amazon_ups.proto

a:
	./src/main/protoc -I=./src/main --java_out=./src/main/java ./src/main/resources/world_amazon.proto

u:
	./src/main/protoc -I=./src/main --java_out=./src/main/java ./src/main/resources/world_ups.proto